version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: podcast
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

   # PHP service with FPM for Laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile  # Use the custom Dockerfile for PHP
    container_name: php-fpm
    ports:
      - "8000:8000"
    volumes:
      - ./podcast:/var/www/html
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data: